[build]
functions = "netlify/functions"
  publish = "build"
  command = "npm run build"

[context.production.environment]
  REACT_APP_API_URL = "https://tu-api-url"
  REACT_APP_ENV = "production"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200